apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # Base64 de "postgres"
  SPRING_DATASOURCE_PASSWORD: bEZMTnpOemw1cCpe
  # url conexao com senha mongodb, base64
  SPRING_DATASOURCE_URL_PAGAMENTO: bW9uZ29kYitzcnY6Ly9wb3N0ZWNoZmlhcHByb2pldG86VE9KSTQ5Y3dvUXFHcEV2TkBmaWFwLjJobWIxLm1vbmdvZGIubmV0L3BhZ2FtZW50b3NfY29sbGVjdGlvbgo=

