apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # Base64 de "postgres"
  SPRING_DATASOURCE_PASSWORD: bEZMTnpOemw1cCpe
  SPRING_DATASOURCE_URL_PAGAMENTO: mongodb+srv://postechfiapprojeto:Fiap@135@fiap.2hmb1.mongodb.net/?retryWrites=true&w=majority&appName=fiap

