apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pagamento-deployment
  labels:
    app:  pagamento-deployment
spec:
  selector:
    matchLabels:
      app: pagamento-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app:  pagamento-deployment
    spec:
      containers:
      - name: pagamento-container
        image: ar989827/ms-pagamento:latest
        ports:
          - containerPort: 8082
        #Liveness Probe
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 110
          periodSeconds: 20
          failureThreshold: 3
        resources:
          limits:
            cpu: 750m 
            memory: 750Mi 
          requests:
            cpu: 250m 
            memory: 250Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: pagamento-config
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SPRING_DATASOURCE_URL_PAGAMENTO