apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pedido-deployment
  labels:
    app:  pedido-deployment
spec:
  selector:
    matchLabels:
      app: pedido-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app:  pedido-deployment
    spec:
      containers:
      - name: pedido-container
        image: ar989827/ms-pedido:latest
        ports:
          - containerPort: 8080
        #Liveness Probe
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 110
          periodSeconds: 20
          failureThreshold: 3
        resources:
          limits:
            cpu: 750m 
            memory: 750Mi 
          requests:
            cpu: 250m 
            memory: 250Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: pedido-config
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: pedido-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SPRING_DATASOURCE_PASSWORD
          - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
            value: org.postgresql.Driver
          - name: SPRING_JPA_HIBERNATE_DDL-AUTO
            valueFrom:
              configMapKeyRef:
                name: pedido-config
                key: SPRING_JPA_HIBERNATE_DDL-AUTO
          - name: SPRING_JPA_DATABASE-PLATFORM
            valueFrom:
              configMapKeyRef:
                name: pedido-config
                key: SPRING_JPA_DATABASE-PLATFORM