name: Deploy to EKS

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List files for debugging
        run: ls -R

      - name: Update kube config
        run: aws eks update-kubeconfig --name dev-fiap-eks-cluster --region us-east-1

      - name: Login to DockerHub
        run: docker login -u ar989827 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Apply ConfigMap and Secrets
        run: |
          kubectl apply -f ms-pedido/pedido-configmap.yaml
          kubectl apply -f ms-producao/pagamento-configmap.yaml
          kubectl apply -f ms-producao/producao-configmap.yaml
          kubectl apply -f secrets.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f ms-pedido/pedido-deployment.yaml
          kubectl apply -f ms-pedido/pedido-srv.yaml
           kubectl apply -f ms-pedido/pagamento-deployment.yaml
          kubectl apply -f ms-pedido/pagamento-srv.yaml
          kubectl apply -f ms-producao/producao-deployment.yaml
          kubectl apply -f ms-producao/producao-srv.yaml